name: routine_generator
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.0

  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^13.0.0  # Check for latest version
  timezone: ^0.9.0  # Timezone package for scheduled notifications
  firebase_core:
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  email_auth: ^2.0.0
  email_otp: ^3.0.1
  get: ^4.6.5
  permission_handler: ^10.2.0  # To request storage permission on Android
  syncfusion_flutter_xlsio: ^20.3.47

  path_provider: ^2.0.11  # Make sure to use the latest version
  open_file: ^3.2.1

  file_picker: ^5.2.3   # For picking the Excel file
  excel: ^2.0.8         # For reading Excel files

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "image/ic_launcher.png" # Replace with your logo path

flutter:
  assets:
    - assets/
  uses-material-design: true