// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3fn0HXNuf38GoW0tSdK9mYRmH-omgBT8',
    appId: '1:983692278734:web:62e9a87f2924d85469499f',
    messagingSenderId: '983692278734',
    projectId: 'routine-generator-5ac7a',
    authDomain: 'routine-generator-5ac7a.firebaseapp.com',
    storageBucket: 'routine-generator-5ac7a.appspot.com',
    measurementId: 'G-ZEED5NYDM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6VFaDki-kWM7IP96nRWPl0C3ByBpDEc8',
    appId: '1:983692278734:android:d7e5e0edc550a82269499f',
    messagingSenderId: '983692278734',
    projectId: 'routine-generator-5ac7a',
    storageBucket: 'routine-generator-5ac7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV851boAjTZF3RXwOxPbKX-SaBsRQrNPk',
    appId: '1:983692278734:ios:6050dace68e2b54e69499f',
    messagingSenderId: '983692278734',
    projectId: 'routine-generator-5ac7a',
    storageBucket: 'routine-generator-5ac7a.appspot.com',
    iosBundleId: 'com.example.routineGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV851boAjTZF3RXwOxPbKX-SaBsRQrNPk',
    appId: '1:983692278734:ios:6050dace68e2b54e69499f',
    messagingSenderId: '983692278734',
    projectId: 'routine-generator-5ac7a',
    storageBucket: 'routine-generator-5ac7a.appspot.com',
    iosBundleId: 'com.example.routineGenerator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3fn0HXNuf38GoW0tSdK9mYRmH-omgBT8',
    appId: '1:983692278734:web:4e21efc390802f5b69499f',
    messagingSenderId: '983692278734',
    projectId: 'routine-generator-5ac7a',
    authDomain: 'routine-generator-5ac7a.firebaseapp.com',
    storageBucket: 'routine-generator-5ac7a.appspot.com',
    measurementId: 'G-QW82PS0NT5',
  );
}
